X x adr xx patch 1
FOSSRIT/hfoss2024-blogs pull request #26
Opened 2024-04-19 18:10 UTC by xXAdrXx

Made the neccessary changes

2024-04-22 13:31 UTC, MoralCode requested changes
Looking better! Just a quick fix to the image paths since they still dont seem to be working.

Also, for future reference, if you push commits to the branch you have a Pull Request for, it will automatically add those commits to the pull request, you dont have to create a new PR every time.

hope this helps!

2024-04-22 13:31 UTC, MoralCode commented on _posts/2024-03-21-fixing-a-godot-doc.md
> +![page editing documentation edit](assets/2024-04-18-Adrian_Marquez_godot_docfix/page_edit_documentation.png)
seems like the images still arent loading, try this: 
```suggestion
![page editing documentation edit](../assets/2024-04-18-Adrian_Marquez_godot_docfix/page_edit_documentation.png)
```

2024-04-22 13:31 UTC, MoralCode commented on _posts/2024-03-21-fixing-a-godot-doc.md
> +![image of the issue](/hfoss2024-blogs/posts/assets/2024-04-18-Adrian_Marquez_godot_docfix/Image_of_issue.png)
```suggestion
![image of the issue](../assets/2024-04-18-Adrian_Marquez_godot_docfix/Image_of_issue.png)
```

try applying this to the rest of the images

2024-04-23 18:50 UTC, xXAdrXx commented
I think I made the necessary changes this time

2024-04-23 23:06 UTC, xXAdrXx commented on _posts/2024-03-21-fixing-a-godot-doc.md
> +![image of the fix](/hfoss2024-blogs/posts/assets/2024-04-18-Adrian_Marquez_godot_docfix/Image_of_fix.png)
i think i did it right this time

2024-04-24 22:23 UTC, MoralCode commented on _posts/2024-03-21-fixing-a-godot-doc.md
> +![image of the fix](/hfoss2024-blogs/posts/assets/2024-04-18-Adrian_Marquez_godot_docfix/Image_of_fix.png)
@xXAdrXx very close! i think in your fix for this particular image you forgot to remove the `posts` part of the URL like you did for the rest of them

2024-04-26 02:56 UTC, xXAdrXx commented
please tell me i did it right

2024-04-26 13:51 UTC, MoralCode commented
> please tell me i did it right

Almost! take a look at the comment I left in the review suggestion above - seems like you forgot to fix one image path

2024-04-26 13:54 UTC, MoralCode commented
Nevermind i didnt see the commit you added. LGTM!

2024-04-26 13:54 UTC, merged